### ISSUE TITLE
open telemetry doesn't work in the example

### ISSUE THREAD

**Issue by mattkanwisher** [andreatosato/Photobook#1]
1) you dont seem to even set a URL in the docker compose, AppSettings__OtelEndpoint=${OTELENDPOINT} , this is just empty
2) if you set a url, then it just fails with this exception, activity is always NULL, so I suspect the application never set this up correctly

``` C#

using var activity = source.StartActivity(SourceName, ActivityKind.Internal)!;
activity.AddEvent <--- this always fails cause activity is null
```
Exception thrown: 'System.NullReferenceException' in Photobook.dll: 'Object reference not set to an instance of an object.'
Stack trace:

**Comment by marcominerva** [comment]
You should add the `${OTELENDPOINT}` setting, as well as all the other keys that are required by the system, in an `.env` file in the same folder of the docker-compose:

```
STORAGEACCOUNTCONNECTION=
COGNITIVESERVICESKEY=
COGNITIVESERVICESENDPOINT=
OTELENDPOINT=http://otel:4317
```

**Comment by mattkanwisher** [comment]
yeah it should be defaulted, it makes no sense why you wouldnt have it in the file. The docker compose doesn't work otherwise, and all other values are in the file

**Comment by marcominerva** [comment]
It isn't true that all the other values are in the docker-compose. Besides `OTELENDPOINT`, the application needs _Storage Account_ and _Cognitive Services_ settings to work properly, and they are sensitive information that cannot be put in the docker-compose for security reason. Probably we can think about putting `OTELENDPOINT` directly in the docker-compose override, but, in any case, you need to have an `.env` file,
